### PR TITLE
Add ability to get spawned child process.

### PR DESCRIPTION
**Pull request by Strate**
Related to #2 

Feature could be used for send messages to child process and receive messages from it.
Useful to build intercommunicating between main thread and child workers.

### CODE REVIEW

**Comment by ohjames** [comment]
This library is only supposed to be a simple process pool, if you want IPC like features then I'd build a wrapper library on top and pass data to the child via the process init part of the function. If you have messages going both ways then it no longer feels like an efficient process pool, the parts that respond to parent data would lose the pooling. It's not something I think is a good idea right now.

Maybe you could convince me with a use case, but I'd probably come up with an alternate suggestion than using pp.

**Comment by Strate** [comment]
Man, I just add a way to get spawned child process. Is it a bad for this library? I can remove an example from readme. As for now, library can not be used as a base to build IPC-featured library.

**Comment by ohjames** [comment]
>As for now, library can not be used as a base to build IPC-featured library.

But it's a process pool, if you want IPC then you don't want a process pool, you want something much more. Libraries should be small and single purpose. You heard of "feature creep" right?

**Comment by Strate** [comment]
Do you really think that it is a really big big big feature - to get reference to spawned child process?

**Comment by ohjames** [comment]
Are you aware the cp.send is sync? Surely that's enough to dissuade you? Why not use an alternative IPC mechanism like named pipes or SHM?

**Comment by ohjames** [comment]
Okay they finally added an async version but still... Why do you want to do unpooled IPC over a library designed to be used as an efficient pool? If you have extra IPC happening inside the pool then you break it's ability to be used as an efficient pool. If you treat a dog as a horse you have an inefficient horse and an inefficient dog in one.

**Comment by Strate** [comment]
Firstly: I am not close with IPC techniques.

I am trying to write `sigh-cssmodules`  plugin. In a fact, it process css files and make classes scoped. Also, it need to *resolve dependencies*, like `@import` directive in css.
This means that compiler should have a whole files tree. If I pass all files to each pooled process, it gives an overhead. I just want to ask other files from parent process only if compiler need them.

How can it be realized?

**Comment by ohjames** [comment]
This should definitely not be done the way you were thinking, it would break the pool. Instead use the return value of the pooled process together with subsequent calls back to the same pool (these subsequent calls *can* be efficiently delegated, IPC in the middle would block the pooled function from being reused).

**Comment by Strate** [comment]
> IPC in the middle would block the pooled function from being reused

I don't knew that, thank you.

Seems that [named pipe](http://stackoverflow.com/a/32172145/1209428) is the answer, yep?

**Comment by ohjames** [comment]
No, that would have the same drawback. Do it by returning data from the pooled process and then reacting to it in the parent.

**Comment by Strate** [comment]
Huh, it could be difficult

**Comment by ohjames** [comment]
Coupling it with bacon.js or some other FRP library, it should be fairly trivial. Unless the response need to access data cached by the pooled VM instance. In that case what you need isn't a "process pool" but something more advanced.

**Comment by ohjames** [comment]
If you are happy with removing the process from the pool while it waits for the response (which may be acceptable if you absolutely know the parent process can reply very quickly) then I'd use a named pipe.

**Comment by Strate** [comment]
> Coupling it with bacon.js or some other FRP library, it should be fairly trivial.

the most difficult thing is split compilation process in two phases:
1. Parse css and extract all import, return in to parent
2. Resolve imports in parent process
3. Pass resolved imports to second phase compiler.

**Comment by ohjames** [comment]
You could just do it all in the child process, it's perfectly fine in sigh to add extra events representing more files from within the pool and return them via an array.

**Comment by Strate** [comment]
Okay, thank you for responses :-)

**Pull request closed without merging**
